/* Auto-generated from .config, do not edit! */
#define CONFIG_ISA_riscv 1
#define CONFIG_ISA riscv32
#define CONFIG_MAX_INST_TO_PRINT 20
#define CONFIG_MBASE 0x80000000
#define CONFIG_MSIZE 0x08000000
#define CONFIG_PC_RESET_OFFSET 0x0
#define CONFIG_DIFFTEST 1
#define CONFIG_TRACE 1
#define CONFIG_TRACE_START 0
#define CONFIG_TRACE_END 1000000
#define CONFIG_ITRACE 1
#define CONFIG_FTRACE 1
#define CONFIG_FTRACE_INDENT 1
#define CONFIG_EXT_M 1
